/**
 * Tailwind bridge — the material adapter for both CSA web surfaces.
 *
 * Everything here is BUILT FROM `tokens.ts`, `light.ts` and `dark.ts`. There is
 * not a single hex, size or radius literal in this file, and there must never
 * be one: the moment either web surface declares a value Tailwind-side, public
 * web, operations web, and the Expo app begin to drift apart.
 *
 * How it fits together:
 *
 *   1. `themeCss()` emits the CSS custom properties for BOTH themes. Paste its
 *      output into a web surface's global stylesheet (or write it at build time).
 *      This is the only place hexes reach the browser, and it is generated.
 *   2. `tailwindTheme` is the Tailwind `theme` fragment. Its colours point at
 *      those custom properties, so `bg-surface-card-ground` resolves to
 *      whichever theme is active without a single `dark:` variant.
 *
 * Because the variables carry the theme, components do not need `dark:` at all.
 * That is also the cleanup step for anything vendored from shadcn/ui: swap its
 * radii for `rounded-control`/`rounded-card`, delete its `dark:` variants, and
 * route its focus ring through the global `:focus-visible` rule.
 *
 * NOTE ON `theme` vs `theme.extend`: place `colors`, `borderRadius`, `fontSize`,
 * `fontFamily` and `spacing` under `theme` and NOT under `theme.extend`. That
 * replaces Tailwind's defaults rather than adding to them, which is deliberate:
 * it removes `rounded-xl`, `text-2xl`, `bg-red-500` and `p-[13px]`-adjacent
 * drift from the vocabulary entirely. If those classes do not exist, nobody has
 * to remember not to use them.
 */

import { motionTokens } from "@csa/motion";

import { hexToRgba } from "./contrast";
import { darkTheme } from "./dark";
import { lightTheme } from "./light";
import {
  elevation,
  fontFamily,
  fontWeight,
  opacity,
  radius,
  size,
  space,
  typeScale,
  type Theme,
} from "./tokens";

/** Prefix for every generated custom property. */
export const CSS_VAR_PREFIX = "csa";

/**
 * Mutably-indexed on purpose: Tailwind's own `colors` type is a mutable
 * recursive record, and a `readonly` index signature here would force every
 * consumer to cast at the config boundary.
 */
export type ColorTree = { [key: string]: string | ColorTree };

/**
 * The colour half of a theme, as a plain nested tree.
 *
 * Both the CSS variables and the Tailwind colour map are generated by walking
 * this one function, so a variable name cannot drift away from the class name
 * that consumes it — they are produced from the same path.
 *
 * `status` deliberately exposes only `solid` and `subtle`. `icon` and `label`
 * are not colours and have no business in a Tailwind palette; components read
 * them from the theme object directly.
 */
export function themeColorTree(theme: Theme): ColorTree {
  const surface = (s: Theme["surface"]["app"]) => ({
    ground: s.ground,
    ink: s.ink,
    "ink-muted": s.inkMuted,
    hairline: s.hairline,
    outline: s.outline,
    "focus-ring": s.focusRing,
  });

  return {
    surface: {
      app: surface(theme.surface.app),
      card: surface(theme.surface.card),
      sunken: surface(theme.surface.sunken),
      overlay: surface(theme.surface.overlay),
    },
    brand: {
      mark: theme.brand.mark,
      solid: surface(theme.brand.solid),
      subtle: surface(theme.brand.subtle),
    },
    status: {
      success: {
        solid: surface(theme.status.success.solid),
        subtle: surface(theme.status.success.subtle),
      },
      warning: {
        solid: surface(theme.status.warning.solid),
        subtle: surface(theme.status.warning.subtle),
      },
      danger: {
        solid: surface(theme.status.danger.solid),
        subtle: surface(theme.status.danger.subtle),
      },
      info: { solid: surface(theme.status.info.solid), subtle: surface(theme.status.info.subtle) },
    },
    link: {
      ink: theme.link.ink,
      hover: theme.link.hover,
      pressed: theme.link.pressed,
    },
    scrim: theme.scrim,
  };
}

/** Flattens a colour tree to `surface-card-ground` -> `#FFFFFF`. */
export function flattenColorTree(tree: ColorTree, prefix = ""): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}-${key}` : key;
    if (typeof value === "string") {
      out[path] = value;
    } else {
      Object.assign(out, flattenColorTree(value, path));
    }
  }
  return out;
}

/** Maps a colour tree's leaves through `fn`, keeping the shape. */
function mapColorTree(tree: ColorTree, fn: (path: string) => string, prefix = ""): ColorTree {
  const out: Record<string, string | ColorTree> = {};
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}-${key}` : key;
    out[key] = typeof value === "string" ? fn(path) : mapColorTree(value, fn, path);
  }
  return out;
}

/** `--csa-surface-card-ground` -> `#FFFFFF`, for one theme. */
export function cssVariablesFor(theme: Theme): Record<string, string> {
  const flat = flattenColorTree(themeColorTree(theme));
  const out: Record<string, string> = {};
  for (const [path, value] of Object.entries(flat)) {
    out[`--${CSS_VAR_PREFIX}-${path}`] = value;
  }
  return out;
}

function declarationsBlock(vars: Record<string, string>, indent: string): string {
  return Object.entries(vars)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join("\n");
}

export interface ThemeCssOptions {
  /**
   * Selector that forces light regardless of system preference.
   * Default `[data-theme="light"]`.
   */
  readonly lightSelector?: string;
  /**
   * Selector that forces dark regardless of system preference.
   * Default `[data-theme="dark"]`.
   */
  readonly darkSelector?: string;
}

/**
 * The full stylesheet fragment: light as the base, dark under
 * `prefers-color-scheme` for users who have expressed no preference, and both
 * available as explicit overrides.
 *
 * The ordering matters and is the usual three-state theming problem: an
 * explicit choice must beat the media query in BOTH directions, which is why
 * the media query is guarded against the light selector rather than left open.
 *
 * `color-scheme` is emitted alongside so that native form controls, scrollbars
 * and the browser's own chrome follow the theme too.
 */
export function themeCss(options: ThemeCssOptions = {}): string {
  const lightSelector = options.lightSelector ?? '[data-theme="light"]';
  const darkSelector = options.darkSelector ?? '[data-theme="dark"]';

  const light = cssVariablesFor(lightTheme);
  const dark = cssVariablesFor(darkTheme);

  return [
    "/* Generated from @csa/design-tokens. Do not edit by hand — edit the tokens. */",
    ":root {",
    "  color-scheme: light;",
    declarationsBlock(light, "  "),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    `  :root:not(${lightSelector}) {`,
    "    color-scheme: dark;",
    declarationsBlock(dark, "    "),
    "  }",
    "}",
    "",
    `:root${darkSelector}, ${darkSelector} {`,
    "  color-scheme: dark;",
    declarationsBlock(dark, "  "),
    "}",
    "",
    `:root${lightSelector}, ${lightSelector} {`,
    "  color-scheme: light;",
    declarationsBlock(light, "  "),
    "}",
    "",
  ].join("\n");
}

/**
 * Tailwind colour map pointing at the generated variables.
 *
 * Built from the light theme's SHAPE only — no light value is baked in. Both
 * themes are asserted to have identical shape in the test, so this map is
 * correct for either.
 */
export const tailwindColors: ColorTree = mapColorTree(
  themeColorTree(lightTheme),
  (path) => `var(--${CSS_VAR_PREFIX}-${path})`,
);

const px = (n: number) => `${n}px`;

/**
 * `Object.fromEntries(Object.entries(x).map(...))` with the tuple typing done
 * once, here, instead of at six call sites.
 *
 * The cast is because `Object.entries` erases value types for a generic object;
 * it is sound by construction — the values came out of `source`.
 */
function mapEntries<T extends object, R>(
  source: T,
  fn: (value: T[keyof T], key: string) => R,
): Record<string, R> {
  const out: Record<string, R> = {};
  for (const [key, value] of Object.entries(source)) {
    out[key] = fn(value as T[keyof T], key);
  }
  return out;
}

/** `space` as a Tailwind spacing scale. Keys are the multiplier, as in the tokens. */
export const tailwindSpacing: Record<string, string> = mapEntries(space, (value) => px(value));

/**
 * Tailwind's tuple form for a font size: the size, then everything that travels
 * with it.
 */
export type TailwindFontSizeEntry = [
  string,
  { lineHeight: string; letterSpacing: string; fontWeight: string },
];

/**
 * The type scale as Tailwind `fontSize` entries.
 *
 * Each entry is the tuple form, so line-height, letter-spacing and weight ride
 * along with the size: `text-body` is the whole step, and there is no reason to
 * ever write `text-body leading-6 tracking-tight` at a call site.
 */
export const tailwindFontSize: Record<string, TailwindFontSizeEntry> = mapEntries(
  typeScale,
  (step): TailwindFontSizeEntry => [
    px(step.size),
    {
      lineHeight: px(step.lineHeight),
      letterSpacing: `${step.letterSpacing}em`,
      fontWeight: String(step.weight),
    },
  ],
);

/** Elevation as `box-shadow` declarations. `flat` is genuinely none. */
export const tailwindBoxShadow: Record<string, string> = mapEntries(elevation, (e) =>
  e.opacity === 0
    ? "none"
    : `0 ${px(e.y)} ${px(e.blur)} ${px(e.spread)} ${hexToRgba(e.color, e.opacity)}`,
);

/**
 * The Tailwind `theme` fragment.
 *
 * Spread this into `theme` (not `theme.extend`) — see the note at the top of
 * this file for why replacing the defaults is the point.
 */
export const tailwindTheme = {
  colors: tailwindColors,
  spacing: tailwindSpacing,
  borderRadius: mapEntries(radius, (v) => px(v)),
  fontFamily: {
    sans: [...fontFamily.sans],
    mono: [...fontFamily.mono],
  },
  fontSize: tailwindFontSize,
  fontWeight: mapEntries(fontWeight, (v) => String(v)),
  boxShadow: tailwindBoxShadow,
  opacity: mapEntries(opacity, (v) => String(v)),
  transitionDuration: mapEntries(motionTokens.duration, (v) => `${v}ms`),
  transitionTimingFunction: mapEntries(motionTokens.easing, (v) => v.css),
  minHeight: {
    /** The accessibility floor. Any pointer-or-touch target on the web uses this. */
    touch: px(size.touchTarget.min),
    "control-sm": px(size.control.sm),
    "control-md": px(size.control.md),
    "control-lg": px(size.control.lg),
  },
  minWidth: {
    touch: px(size.touchTarget.min),
  },
};

/**
 * Tailwind `darkMode` config matching `themeCss()`'s selectors.
 *
 * Mostly unnecessary — the custom properties flip on their own, so components
 * should not need `dark:` at all. It exists for the rare case where dark needs
 * a genuinely different layout rather than a different colour, and for stripping
 * `dark:` out of vendored shadcn components without breaking them mid-edit.
 */
export const tailwindDarkMode: [string, string[]] = ["variant", ['&:is([data-theme="dark"] *)']];

/** Re-exported for web adapters; `@csa/motion` remains the sole owner. */
export { motionTokens } from "@csa/motion";

export default tailwindTheme;
