/**
 * Turns the in-memory estate into the files an extract would actually produce.
 *
 * Each source emits in its own native format, and none of them is pre-joined.
 * A convenience dump that already stitches members to payments has made a
 * transform decision inside the extract, where nobody reviews it — the ETL
 * standard rules that out, and this is where that rule is kept.
 */
import type { FormResponse, LedgerEntry, LegacyEstate, MolliePayment, WpItem } from "./types";

/** RFC 4180: quote everything, double the quotes inside. Never guess about commas. */
function csvCell(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

export function toCsv(headers: readonly string[], rows: ReadonlyArray<readonly string[]>): string {
  const lines = [headers.map(csvCell).join(",")];
  for (const row of rows) lines.push(row.map(csvCell).join(","));
  return lines.join("\r\n") + "\r\n";
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function cdata(value: string): string {
  // A CDATA section cannot contain "]]>", and WordPress splits it the same way.
  return `<![CDATA[${value.replace(/]]>/g, "]]]]><![CDATA[>")}]]>`;
}

/**
 * A WordPress eXtended RSS export.
 *
 * Deliberately the real format rather than a convenient JSON stand-in: WXR is
 * what a committee can actually produce from wp-admin without a developer, and
 * an importer that only reads a shape nobody can export is an importer that
 * cannot be used on the day.
 */
export function toWxr(items: readonly WpItem[]): string {
  const body = items
    .map((item) => {
      const meta = Object.entries(item.postmeta)
        .map(
          (entry) =>
            `\t\t<wp:postmeta>\n\t\t\t<wp:meta_key>${cdata(entry[0])}</wp:meta_key>\n` +
            `\t\t\t<wp:meta_value>${cdata(entry[1])}</wp:meta_value>\n\t\t</wp:postmeta>`,
        )
        .join("\n");
      return [
        "\t<item>",
        `\t\t<title>${cdata(item.title)}</title>`,
        `\t\t<link>${xmlEscape(item.link)}</link>`,
        `\t\t<pubDate>${xmlEscape(item.pubDate)}</pubDate>`,
        `\t\t<dc:creator>${cdata("csa-webmaster")}</dc:creator>`,
        `\t\t<content:encoded>${cdata(item.content)}</content:encoded>`,
        `\t\t<wp:post_id>${item.postId}</wp:post_id>`,
        `\t\t<wp:post_name>${cdata(item.slug)}</wp:post_name>`,
        `\t\t<wp:status>${cdata(item.status)}</wp:status>`,
        `\t\t<wp:post_type>${cdata(item.postType)}</wp:post_type>`,
        meta,
        "\t</item>",
      ]
        .filter((line) => line !== "")
        .join("\n");
    })
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8" ?>',
    "<!-- Synthetic fixture. Generated by @csa/legacy-fixtures; no CSA system was read. -->",
    '<rss version="2.0"',
    '\txmlns:content="http://purl.org/rss/1.0/modules/content/"',
    '\txmlns:dc="http://purl.org/dc/elements/1.1/"',
    '\txmlns:wp="http://wordpress.org/export/1.2/">',
    "<channel>",
    "\t<title>CSA Rotterdam (fixture)</title>",
    "\t<link>https://csa-rotterdam.nl</link>",
    "\t<wp:wxr_version>1.2</wp:wxr_version>",
    "\t<wp:base_site_url>https://csa-rotterdam.nl</wp:base_site_url>",
    body,
    "</channel>",
    "</rss>",
    "",
  ].join("\n");
}

/** MongoDB extended JSON, one document per line, as `mongoexport` writes it. */
export function toJsonl(docs: ReadonlyArray<Record<string, unknown>>): string {
  return docs.map((d) => JSON.stringify(d)).join("\n") + "\n";
}

export function formsCsv(rows: readonly FormResponse[]): string {
  return toCsv(
    ["Row ID", "Timestamp", "Email Address", "Full name", "Which event?", "Are you a member?"],
    rows.map((r) => [
      r.rowId,
      r.timestamp,
      r.emailAddress,
      r.fullName,
      r.whichEvent,
      r.memberAnswer,
    ]),
  );
}

export function mollieCsv(rows: readonly MolliePayment[]): string {
  return toCsv(
    ["id", "status", "amount", "description", "createdAt", "method"],
    rows.map((r) => [r.id, r.status, r.amount, r.description, r.createdAt, r.method]),
  );
}

export function ledgerCsv(rows: readonly LedgerEntry[]): string {
  return toCsv(
    ["row_id", "datum", "naam", "email", "bedrag", "afgehandeld_door", "opmerkingen"],
    rows.map((r) => [r.rowId, r.date, r.name, r.email, r.amount, r.handledBy, r.notes]),
  );
}

/**
 * Counts as `{ entity: { year: n } }`.
 *
 * Nested rather than flat, because the reconciliation is per entity AND per
 * year: a total that matches while 2019 is short by 40 and 2023 is long by 40
 * is exactly the failure an aggregate hides. A row whose year cannot be read
 * lands under `unknown` and stays visible rather than being dropped or guessed.
 */
export type ExtractCounts = Readonly<Record<string, Readonly<Record<string, number>>>>;

/**
 * Money as measured at extract time, keyed by the SOURCE's own status
 * vocabulary and then by year.
 *
 * Recorded here rather than recomputed later for the same reason the row counts
 * are: the financial half of a reconciliation is only worth something if its
 * source side was measured before anything transformed it. The statuses are
 * Mollie's, not the contract's — folding `expired` into `failed` is a transform
 * decision, and it belongs where transform decisions are reviewed, not inside
 * the measurement it is checked against.
 */
export type ExtractAmounts = Readonly<
  Record<string, Readonly<Record<string, { readonly rows: number; readonly cents: number }>>>
>;

export interface ExtractFile {
  readonly path: string;
  readonly sourceSystem: string;
  readonly contents: string;
  /** What the extract counts, before any transform touches it. */
  readonly counts: ExtractCounts;
  /** Present only for a source that carries money. */
  readonly amounts?: ExtractAmounts;
  readonly schemaVersion: string;
}

/** Every file an extract of this estate produces, in a stable order. */
export function emitAll(estate: LegacyEstate): ExtractFile[] {
  const byYear = (values: readonly string[]): Record<string, number> => {
    const out: Record<string, number> = {};
    for (const v of values) {
      const year = /(\d{4})/.exec(v)?.[1] ?? "unknown";
      out[year] = (out[year] ?? 0) + 1;
    }
    return out;
  };

  return [
    {
      path: "wordpress/csa-rotterdam.wordpress.xml",
      sourceSystem: "wordpress",
      contents: toWxr(estate.wordpress),
      // Disjoint on purpose. Overlapping buckets make the arithmetic
      // `target + quarantined + merged - source` meaningless: a row counted
      // twice on the source side can only ever be counted once on the target.
      counts: {
        events: byYear(
          estate.wordpress.filter((i) => i.postType === "csa_event").map((i) => i.pubDate),
        ),
        content: byYear(
          estate.wordpress.filter((i) => i.postType !== "csa_event").map((i) => i.pubDate),
        ),
      },
      schemaVersion: "wxr-1.2",
    },
    {
      path: "mongodb/members.jsonl",
      sourceSystem: "mongodb",
      contents: toJsonl(estate.mongo.members as unknown as Record<string, unknown>[]),
      counts: { members: byYear(estate.mongo.members.map((m) => m.created_at)) },
      schemaVersion: "members-v3",
    },
    {
      path: "mongodb/memberships.jsonl",
      sourceSystem: "mongodb",
      contents: toJsonl(estate.mongo.memberships as unknown as Record<string, unknown>[]),
      counts: { memberships: byYear(estate.mongo.memberships.map((m) => m.start_date)) },
      schemaVersion: "memberships-v3",
    },
    {
      path: "google_forms/event-signups.csv",
      sourceSystem: "google_forms",
      contents: formsCsv(estate.forms.eventSignups),
      counts: { registrations: byYear(estate.forms.eventSignups.map((r) => r.timestamp)) },
      schemaVersion: "forms-export-2026",
    },
    {
      path: "google_forms/actives-recruitment.csv",
      sourceSystem: "google_forms",
      contents: formsCsv(estate.forms.actives),
      counts: { applications: byYear(estate.forms.actives.map((r) => r.timestamp)) },
      schemaVersion: "forms-export-2026",
    },
    {
      path: "mollie/payments.csv",
      sourceSystem: "mollie",
      contents: mollieCsv(estate.mollie),
      counts: { payments: byYear(estate.mollie.map((p) => p.createdAt)) },
      amounts: (() => {
        const out: Record<string, Record<string, { rows: number; cents: number }>> = {};
        for (const p of estate.mollie) {
          const year = /(\d{4})/.exec(p.createdAt)?.[1] ?? "unknown";
          const status = (out[p.status] ??= {});
          const bucket = (status[year] ??= { rows: 0, cents: 0 });
          bucket.rows += 1;
          // The fixture writes plain `12.34`; a real export needs the same
          // conservative parse the importer uses, and would refuse rather than
          // guess. Here the format is known because this file wrote it.
          bucket.cents += Math.round(Number(p.amount) * 100);
        }
        return out;
      })(),
      schemaVersion: "mollie-export-v2",
    },
    {
      path: "office_ledger/register.csv",
      sourceSystem: "office_ledger",
      contents: ledgerCsv(estate.ledger),
      counts: { members: byYear(estate.ledger.map((e) => e.date)) },
      schemaVersion: "paper-register",
    },
  ];
}
