import type { UserRole } from "@csa/domain";

/**
 * Contract §7. Auth in this prototype is seeded sessions: magic link is not
 * available because `.local` is undeliverable, so "signing in" means picking
 * one of these four fictional identities.
 *
 * The emails are the stable handle — ids are generated by the seed and change
 * every time it is re-run, so nothing here hardcodes a uuid. The ids are looked
 * up at request time in `lib/data.ts`.
 *
 * These are FICTIONAL. There is no real member, ticket or payment data anywhere
 * in this repo, and there must never be.
 */

export interface DemoIdentitySpec {
  readonly email: string;
  /** Why a demonstrator would pick this one. Shown in the switcher. */
  readonly purpose: string;
}

export const DEMO_IDENTITY_EMAILS = [
  "admin@demo.local",
  "staff@demo.local",
  "member@demo.local",
  "nonmember@demo.local",
] as const;

export type DemoIdentityEmail = (typeof DEMO_IDENTITY_EMAILS)[number];

export const DEMO_IDENTITIES: readonly DemoIdentitySpec[] = [
  { email: "admin@demo.local", purpose: "Full committee access" },
  { email: "staff@demo.local", purpose: "Door and check-in duty" },
  { email: "member@demo.local", purpose: "Active membership — member pricing" },
  { email: "nonmember@demo.local", purpose: "No membership — public pricing" },
];

export function isDemoIdentityEmail(value: unknown): value is DemoIdentityEmail {
  return (
    typeof value === "string" &&
    (DEMO_IDENTITY_EMAILS as readonly string[]).includes(value.toLowerCase())
  );
}

/**
 * Contract §2: role governs PERMISSIONS ONLY. It is never an input to pricing —
 * that comes from an active membership period at registration time. This helper
 * is about what the portal will show you, and nothing else.
 */
export function isCommitteeRole(role: UserRole): boolean {
  return role === "staff" || role === "admin";
}

export const ROLE_LABEL: Record<UserRole, string> = {
  admin: "Admin",
  staff: "Staff",
  attendee: "Attendee",
};
